Lab-ASPNET/Controllers/ComputerController.cs
using Lab_ASPNET.Models;
using Lab_ASPNET.Services.Computery;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace Lab_ASPNET.Controllers
{
    [Authorize(Roles = "admin")]
    public class ComputerController : Controller
    {
        private static Dictionary<int, Computer> _computers = new Dictionary<int, Computer>();

        private readonly IComputerService _computerService;

        public ComputerController(IComputerService computerService)
        {
            _computerService = computerService;
        }
        public IActionResult Index()
        {
            var Computers = _computerService.Find();
            return View(Computers);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            _computerService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            Computer model = new Computer();
            model.Producers = _computerService
                .FindAllProducents()
                .Select(o => new SelectListItem() { Value = o.Id.ToString(), Text = o.Title })
                .ToList();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Computer model)
        {
            if (ModelState.IsValid)
            {
                _computerService.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                model.Producers = _computerService
                    .FindAllProducents()
                    .Select(o => new SelectListItem() { Value = o.Id.ToString(), Text = o.Title })
                    .ToList();
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var Computer = _computerService.FindComputerById(id);
            if (Computer == null)
            {
                return NotFound();
            }
            return View(Computer);
        }

        [HttpPost]
        public IActionResult Edit(Computer model)
        {
            if (ModelState.IsValid)
            {
                _computerService.Update(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }


        [HttpGet]
        public IActionResult Details(int id)
        {
            var Computer = _computerService.FindComputerById(id);
            if (Computer == null)
            {
                return NotFound();
            }
            return View(Computer);
        }

    }
}

Lab-ASPNET/Controllers/ProducerController.cs
using Lab_ASPNET.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Lab_ASPNET.Services.Producery;


namespace Lab_ASPNET.Controllers
{
    public class ProducerController : Controller
    {
        private static Dictionary<int, Producer> _producers = new Dictionary<int, Producer>();

        private readonly IProducerService _producerService;

        public ProducerController(IProducerService producerService)
        {
            _producerService = producerService;
        }
        public IActionResult Index()
        {
            var Producers = _producerService.Find();
            return View(Producers);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            _producerService.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
            Producer model = new Producer();
            model.Producers = _producerService
                .FindAllProducents()
                .Select(o => new SelectListItem() { Value = o.Id.ToString(), Text = o.Title })
                .ToList();
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Producer model)
        {
            if (ModelState.IsValid)
            {
                _producerService.Add(model);
                return RedirectToAction("Index");
            }
            else
            {
                model.Producers = _producerService
                    .FindAllProducents()
                    .Select(o => new SelectListItem() { Value = o.Id.ToString(), Text = o.Title })
                    .ToList();
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var producer = _producerService.FindProducerById(id);
            if (producer == null)
            {
                return NotFound();
            }
            return View(producer);
        }

        [HttpPost]
        public IActionResult Edit(Producer model)
        {
            if (ModelState.IsValid)
            {
                _producerService.Update(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }


        [HttpGet]
        public IActionResult Details(int id)
        {
            var producer = _producerService.FindProducerById(id);
            if (producer == null)
            {
                return NotFound();
            }
            return View(producer);
        }
    }
}

Lab-ASPNET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab_ASPNET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab_ASPNET.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab_ASPNET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                                         <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Computer" asp-action="Index">Komputery</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Computer" asp-action="Create">Dodaj komputer</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-controller="Producer" asp-action="Index">Producenci</a>
                 </li>
                 <partial name="_LoginPartial" />
             </ul>
                    </ul>
                </div>
            </div>
        </nav>      
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Lab_ASPNET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>